### ISSUE TITLE
CallFunction(...) Arguments exceed max args length of 63

### ISSUE THREAD

**Issue by ghost** [spark/spark-sdk-android#4]
After upgrading to the io.particle:cloudsdk:0.2.2, the CallFunction() seems added a limitation on the argument length that breaks my App.

Could someone explain why the limit is set to 63 and would this be changed in the future sdk versions? It would be rather inefficient if I have to break the current argument and send in two steps.

Thanks!

Stack trace:

 java.lang.RuntimeException: An error occured while executing doInBackground()
                                                                         at android.os.AsyncTask$3.done(AsyncTask.java:300)
                                                                         at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
                                                                         at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
                                                                         at java.util.concurrent.FutureTask.run(FutureTask.java:242)
                                                                         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                         at java.lang.Thread.run(Thread.java:818)
                                                                      Caused by: java.lang.IllegalArgumentException: Arguments 'cnt=8000|rdt=9000|mtt=11000|mot=8000|rlt=1500|rlp=1000|srr=19|srt=29' exceed max args length of 63
                                                                         at com.google.common.base.Preconditions.checkArgument(Preconditions.java:122)
                                                                         at io.particle.android.sdk.cloud.ParticleDevice.callFunction(ParticleDevice.java:265)
                                                                         at com.rwmobi.garadget.activities.SettingsActivity$3.callApi(SettingsActivity.java:257)
                                                                         at com.rwmobi.garadget.activities.SettingsActivity$3.callApi(SettingsActivity.java:253)
                                                                         at io.particle.android.sdk.utils.Async$AsyncApiWorker.doInBackground(Async.java:103)
                                                                         at io.particle.android.sdk.utils.Async$AsyncApiWorker.doInBackground(Async.java:71)
                                                                         at android.os.AsyncTask$2.call(AsyncTask.java:288)
                                                                         at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
                                                                         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
                                                                         at java.lang.Thread.run(Thread.java:818)

**Comment by idokleinman** [comment]
Actually max argument length of 63 characters is limitation of Core & Photon devices not the SDK.

**Comment by jensck** [comment]
@ry-wong Ido is correct, this limitation isn't an SDK issue; closing.
